---
version: "~> 1.0"
os: linux
language: shell
services: docker
notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    if: branch = master
    rooms:
      secure: Et8yz+XGKhS6qotEjOpYtuW4ZeQkOEx1COv6ZKfTzvYKZ9H8Vu/Y669TmJ/RL/Mnh39svtul9cRthuLYj+Wh2Glvvs0EYj/fj+k3xb173qdIsS760b8qp4M15zsSX8rZ657NUnDPnw5IA4t1PZqYTXPhpTuG73rYZY8cZhV173TgBp+IeYgwHSxgplYSXP9z4dxLTx+pFczlHJo8sTg58Sgb+ppVdxU/A4luBgqnX9mPuBoEEmXfuAFnhLr/pvoItRAlU9dvNZeYshQmNYUdQ49x3CHOpKvigtdzh7d65xqXRMHb3vFxQElLw8X5Mfpsh2QcP+St+9OiU45Q1ENLO0yKMcmiEVQBpTLEMiYakZiXC9J56hf7X6aBUHevlY5Hnc6SK51LWNxD6c/p6d2DGiE+SawIjB8f9KbwPwXHsd6sOFQT1s6IODKJ8bPa7jclRZm3zDRAhq0X2sy2rcvdYXGb8sLjnkKRsu2JOImlKmKfxi0oJqcOldjgsDndXgdaZjfExQH0HGU+2OwmFiyeYUb51VKMzUZmBUgodgWEC7JPvdclsATrtWdA0tlNh4ZPLFW+68p3c8Jfxg4KS93OZuHFw0H1tiZmY/VjuiuL1kIF0d5O3ORy9YF1oAPtpotz8UEoYBeACxuSVatBS1SAQIPTXfOp91Vv7AuEKGEodL4=
    template:
    - "%{commit_subject}"
    - build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) @%{branch}
    - by %{author} %{result} in %{duration}
    on_success: change
    on_failure: always

jobs:
  include:
    - env: TAG=latest
    - if: branch = master
      env: TAG=1
    # - if: branch = master
    #   env: TAG=2
    # - if: branch = master
    #   env: TAG=2
script: 
  - . .ci/01_checkout_git_tag.sh
  - . .ci/02_set_build_variables.sh
  - . .ci/03_build_container.sh
  - . .ci/04_terraform_validate.sh
  - . .ci/05_docker_login.sh
  - . .ci/06_docker_push.sh
...