= AWS CDK Java Training provisioning

This application is used to provision an AWS EC2 backed infrastructure depending on the provided configuration. +
See the follwoing section on how to provide a configuration and how to provision/de-provision the AWS infrastructure.

== Provide the configuration

The configuration for the AWS infrastructure is provided via a json file named `configuration.json` which defines the
following configurations.

* `id` +
A unique id string, which is added as a tag to all created resources
* `account` +
The account which provisions the AWS infrastructure, must correlate to the provided aws credentials
* `region` +
The region to the deploy the AWS infrastructure to
* `ami` +
The ami-id of the underlying x86 platform supporting EC2 image to use
* `instanceCount` +
The count of EC2 instances to create

.Configuration example
[source,sh]
----
{
  "id": "containerizationTrainingGepardecLinz",
  "account": "***",
  "region": "eu-central-1",
  "ami": "ami-06b4d9ba1f23a8da4",
  "instanceCount": 1
}
----

IMPORTANT: Don't change the id after a AWS infrastructure has been provisioned, because otherwise it cannot be destroyed anymore.

== How to bootstrap your training environment

You can configure your training environment with a bootstrap script file named `bootstrap.sh`. +

IMPORTANT: The script must be executable on the used Linux distribution you defined via the `ami` configuration parameter.

== How to provision/de-provision an AWS infrastructure

The AWS infrastructure is packaged to a JAR and packaged in a Container-Image which provides all necessary tooling for
provisioning/de-provisioning the AWS infrastructure. The only thing you need is to have a initialized cdk in AWS CloudFormation,
which is used to create your infrastructure stack.

The following commands are the main commands for the aws cdk tooling:

. `synth` (Default without a command) +
Synthesizes the AWS infrastructure by creating the cloud formation resources which get deployed.
Can be used to check if the configuration is valid and if the tolling works.
. `deploy` +
Synthesizes and deploys the AWS infrastructure with cloud formation.
. `destroy` +
Destroy the AWS infrastructure stack.

The configuration is mapped into the container as volumes and the necessary mounts are:

. `<YOUR_LOCAL_AWS_CONFIG_DIR>:/root/.aws` +
The `.aws` directory on your maschine which is used to provision/de-provision the AWS infrastructure
. `<YOUR_LOCAL_CONFIG_DIRECTORY>:/config` +
The configuration directory containing the `configuration.json` and optionally a `bootstra.sh` file for configuring
and preparing your training environment. this directory will also receive the generated ssh-key-pairs, generated
during the provisioning.

.Provision AWS infrastructure
[source, sh]
----
docker run \
    -v $(echo ~)/.aws:/root/.aws:ro \
    -v$(pwd)/config:/config  \
    train-aws-cdk:latest [synth | deploy | destroy]
----

IMPORTANT: See the logs for the public IPs and the DNS names of the created EC2 instances.